version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/da
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/hartl_rails_4_2_sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
